### ISSUE TITLE
maven failed to find dependence

### ISSUE THREAD

**Issue by mikewin** [dwicke/TSAT#1]
mvn package -Psingle

Could not resolve dependencies for project net.seninp:grammarviz2:jar:0.0.1-SNAPSHOT: Failure to find com.github.jMotif:sax-vsm_classic:jar:ebd3ab8

**Comment by dwicke** [comment]
I've updated the pom (forgot to push it last week) and I've tested install from a fresh Ubuntu 16.04 VM and it successfully builds and runs.
