### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by mikewin** [dwicke/TSAT#2]
the files in /data  directory are not RPM format.

Please give some example RPM data for test.

Thanks

**Comment by dwicke** [comment]
I've modified the CBF (Cylinder-Bell-Funnel) dataset to be in the TSAT RPM format and removed the old versions.  The CBF data is referenced in RPM paper https://pdfs.semanticscholar.org/41ed/0d295d76b387bf1e4d13ee99a1511c338756.pdf
