### ISSUE TITLE
How to generate representative pattern candidates

### ISSUE THREAD

**Issue by Deepakgthomas** [dwicke/TSAT#3]
Hello,

I was wondering if there is a way to generate representative pattern candidates using this tool. Essentially, I am talking about section 3.2.2 of the paper, "RPM: Representative Pattern Mining for Efficient Time Series Classification."
I do see that there is a 'Run RPM' section in your GUI, but I am unable to use it. Perhaps, I might be missing something. I will appreciate it if you could kindly help me in this regard.

![image](https://user-images.githubusercontent.com/21986394/58911819-4f21fd00-86de-11e9-8849-3dc95aa9991c.png)

Thank you,
Deepak Thomas

**Comment by dwicke** [comment]
Hi,

Thanks for the question.  Chapter five in the user manual covers how to use
RPM:

https://github.com/dwicke/TSAT/blob/master/user_manual/UserManual.pdf

Thanks,
Drew

**Comment by Deepakgthomas** [comment]
Thanks Drew!
